name: Pulumi Preview and Deploy
on:
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pulumi
        uses: pulumi/actions@v5

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: NPM install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./dev
          npm install

      - name: Create Preview JSON
        id: preview_json
        run: |
          mkdir -p .pulumi
          pulumi preview --json --stack clients-dev --cwd dev/clients > .pulumi/preview.json
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

      - name: Check for Changes
        id: check_changes
        run: |
          CHANGES=$(cat .pulumi/preview.json | jq -r '.changeSummary | select(.create != 0 or .update != 0 or .delete != 0 or .replace != 0)')
          if [ ! -z "$CHANGES" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in preview:"
            echo "$CHANGES" | jq '.'
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in preview"
          fi

      - name: Save Preview State
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Save preview metadata
          echo "$(date -u)" > .pulumi/preview-metadata.txt
          echo "Commit: ${{ github.sha }}" >> .pulumi/preview-metadata.txt
          echo "Workflow: ${{ github.workflow }}" >> .pulumi/preview-metadata.txt

      - name: Upload Preview Artifact
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pulumi-preview-state
          path: .pulumi/
          retention-days: 1

  deploy:
    needs: preview
    if: needs.preview.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pulumi
        uses: pulumi/actions@v5

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: NPM install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./dev
          npm install

      - name: Download Preview State
        uses: actions/download-artifact@v4
        with:
          name: pulumi-preview-state
          path: .pulumi

      - name: Verify State Match
        id: verify_state
        run: |
          # Get current state hash
          CURRENT_PREVIEW=$(pulumi preview --json --stack clients-dev --cwd dev/clients)
          CURRENT_HASH=$(echo "$CURRENT_PREVIEW" | jq -r '.checkpoint_hash')
          
          # Get saved preview hash
          SAVED_HASH=$(cat .pulumi/preview.json | jq -r '.checkpoint_hash')
          
          if [ "$CURRENT_HASH" != "$SAVED_HASH" ]; then
            echo "::error::Stack state has changed since preview. Aborting deployment for safety."
            exit 1
          fi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

      - name: Pulumi Up
        id: deploy
        if: success()
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: clients-dev
          work-dir: dev/clients
          diff: true
          expect-no-changes: false
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

      - name: Save Deployment Results
        if: success()
        run: |
          mkdir -p deployment-outputs
          {
            echo "Deployment completed at: $(date)"
            echo "Commit: ${{ github.sha }}"
            echo "Workflow: ${{ github.workflow }}"
            echo "Actor: ${{ github.actor }}"
            echo "---"
            echo "Preview timestamp: $(cat .pulumi/preview-metadata.txt)"
            echo "---"
            echo "Deployment Output:"
            echo "${{ steps.deploy.outputs.output }}"
          } > deployment-outputs/deployment-results.txt

      - name: Upload Deployment Results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: deployment-results
          path: deployment-outputs/
          retention-days: 90